default['mysql']['db']['user'] = 'saji'
default['mysql']['db']['pass'] = 'saji'
default['mysql']['db']['database'] = 'livdesn'
default['mysql']['db']['test_db'] = 'test_livdesn'
default['mysql']['db']['host'] = 'localhost'
default['mysql']['db']['rootpass'] = ''
