CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) unique
);

CREATE TABLE themes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    description TEXT DEFAULT NULL
);

CREATE TABLE maps (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    description TEXT DEFAULT NULL,
    user_id INT,
    theme_id INT DEFAULT NULL,
    imagename VARCHAR(50) DEFAULT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL
);

CREATE TABLE maps_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    map_id INT,
    user_id INT
);